[ejs.landing]
updateAvailableTooltip = "Atualização Disponível"
usernamePlaceholder = "Nome de Usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Não&nbsp;Essencial"
newsButton = "NOTÍCIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum Servidor Selecionado"
launchDetails = "Por favor, aguarde.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando Notícias.."
newsErrorFailedSpan = "Falha ao Carregar Notícias"
newsErrorRetryButton = "Tentar Novamente"
newsErrorNoneSpan = "Sem Notícias"
minecraftAccount = "Conta Minecraft"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN MINECRAFT"
loginEmailError = "* Valor Inválido"
loginEmailPlaceholder = "EMAIL OU NOME DE USUÁRIO"
loginPasswordError = "* Obrigatório"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "esqueceu a senha?"
loginRememberMeText = "lembrar de mim?"
loginButtonText = "ENTRAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Precisa de uma Conta?"
loginPasswordDisclaimer1 = "Sua senha é enviada diretamente para a Mojang e nunca é armazenada."
loginPasswordDisclaimer2 = "{appName} não é afiliado à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opções de Login"
loginWithMicrosoft = "Entrar com Microsoft"
loginWithMojang = "Entrar com Mojang"
loginWithNickname = "Entrar com Nick"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecionar uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Concluído"
tabAccountHeaderText = "Configurações da Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adicionar Conta Microsoft"
offlineAccount = "Com Nick"
addOfflineAccount = "+ Adicionar uma conta por Nick"
mojangAccount = "Mojang"
addMojangAccount = "+ Adicionar Conta Mojang"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relacionadas ao lançamento do jogo."
gameResolutionTitle = "Resolução do Jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Iniciar o processo do jogo separado do launcher."
launchDetachedDesc = "Se o jogo não estiver separado, fechar o launcher também fechará o jogo."
tabModsHeaderText = "Configurações de Mods"
tabModsHeaderDesc = "Habilitar ou desabilitar mods."
switchServerButton = "Trocar"
requiredMods = "Mods Necessários"
optionalMods = "Mods Opcionais"
dropinMods = "Mods de Inserção"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para Atualizar)"
shaderpacks = "Pacotes de Shader"
shaderpackDesc = "Habilitar ou desabilitar shaders. Observe que shaders só funcionarão suavemente em setups poderosos. Você pode adicionar pacotes personalizados aqui."
selectShaderpack = "Selecionar Pacote de Shader"
tabJavaHeaderText = "Configurações do Java"
tabJavaHeaderDesc = "Gerencie a configuração do Java (avançado)."
memoryTitle = "Memória"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "A RAM mínima recomendada é de 3 gigabytes. Configurar os valores mínimo e máximo como o mesmo valor pode reduzir o lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável do Java"
javaExecSelDialogTitle = "Selecionar Executável do Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executável do Java é validado antes do início do jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções Adicionais da JVM"
jvmOptsDesc = "Opções a serem fornecidas à JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> não devem ser incluídos."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações Pré-Lançamento."
allowPrereleaseDesc = "Pré-Lançamentos incluem novos recursos que podem não ter sido totalmente testados ou integrados.<br>Isso sempre será verdade se você estiver usando uma versão pré-lançamento."
dataDirectoryTitle = "Diretório de Dados"
selectDataDirectory = "Selecionar Diretório de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalações locais do Java serão armazenados no diretório de dados.<br>Capturas de tela e salvamentos de mundos são armazenados na pasta da instância para a configuração de servidor correspondente."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Visualize informações e notas de lançamento para a versão atual."
aboutTitle = "{appName}"
stableRelease = "Lançamento Estável"
versionText = "Versão "
sourceGithub = "Fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console de Ferramentas de Desenvolvimento"
releaseNotes = "Notas de Lançamento"
changelog = "Notas de Mudança"
noReleaseNotes = "Sem Notas de Lançamento"
viewReleaseNotes = "Ver Notas de Lançamento no GitHub"

launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise atualizações para o launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "O que há de Novo"
updateReleaseNotes = "Notas de Lançamento da Atualização"

[ejs.waiting]
waitingText = "Aguardando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Aguardando o Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "ENTRAR"
loggingIn = "ENTRANDO"
success = "SUCESSO"
tryAgain = "Tentar Novamente"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Obrigatório"

[js.login.error.unknown]
title = "Erro Desconhecido Durante o Login"
desc = "Ocorreu um erro desconhecido. Por favor, verifique o console para mais detalhes."

[js.landing.launch]
pleaseWait = "Por favor, aguarde.."
failureTitle = "Erro Durante o Lançamento"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma Conta Selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum Servidor Selecionado"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando informações do sistema.."
noCompatibleJava = "Nenhuma Instalação de<br>Java Compatível Encontrada"
installJavaMessage = "Para iniciar o Minecraft, você precisa de uma instalação de Java {major} de 64 bits. Gostaria que fizéssemos a instalação?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Download do Java.."
javaDownloadFailureTitle = "Erro Durante o Download do Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java é Necessário<br>para Iniciar"
javaRequiredMessage = 'Uma instalação válida de Java {major} x64 é necessária para iniciar.<br><br>Por favor, consulte nosso <a href="https://discord.gg/jornadascobblemon">discord</a> para instruções sobre como instalar o Java manualmente.'
javaRequiredDismiss = "Entendi"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar a distribuição do OpenJDK."
javaDownloadCorruptedError = "O JDK baixado tem um hash inválido, o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informações do servidor.."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Não foi possível carregar uma cópia do índice de distribuição. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Por favor, aguarde.."
errorDuringLaunchTitle = "Erro Durante o Lançamento"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando a integridade do arquivo.."
errorDuringFileVerificationTitle = "Erro Durante a Verificação do Arquivo"
downloadingFiles = "Baixando arquivos.."
errorDuringFileDownloadTitle = "Erro Durante o Download do Arquivo"
preparingToLaunch = "Preparando para iniciar.."
launchingGame = "Iniciando o jogo.."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, falhou ao ser baixado corretamente. Como resultado, o jogo não pode ser iniciado.<br><br>Para corrigir este problema, desative temporariamente o seu software antivírus e inicie o jogo novamente.<br><br>Se possível, por favor, <a href=\"https://discord.gg/jornadascobblemon\">entre no nosso discord</a> e informe qual software antivírus você usa. Entraremos em contato com eles e tentaremos resolver a situação."
doneEnjoyServer = "Concluído. Aproveite o servidor!"
checkConsoleForDetails = "Por favor, verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Verificando Notícias"

[js.landing.discord]
loading = "Entrando na jornada!"
joining = "Vivendo minha jornada!"
joined = "Vivendo minha jornada!"

[js.overlay]
dismiss = "Fechar"

[js.settings.fileSelectors]
executables = "Executáveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo Deu Errado"
errorMessage = "A autenticação Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Deu Errado"
errorMessage = "O logout da Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Aviso<br>Esta é Sua Última Conta"
lastAccountWarningMessage = "Para usar o launcher, você deve estar logado em pelo menos uma conta. Você precisará fazer login novamente depois.<br><br>Tem certeza de que deseja sair?"
confirmButton = "Tenho Certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nome de Usuário"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada ✓"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao Deletar<br>Mod de Inserção {fullName}"
deleteFailedMessage = "Certifique-se de que o arquivo não está em uso e tente novamente."
failedToggleTitle = "Falha ao Alternar<br>Um ou Mais Mods de Inserção"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Seleção Inválida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opções Disponíveis para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-Lançamento"
stableReleaseTitle = "Lançamento Estável"
releaseNotesFailed = "Falha ao carregar as notas de lançamento."

[js.settings.updates]
newReleaseTitle = "Novo Lançamento Disponível"
newPreReleaseTitle = "Novo Pré-Lançamento Disponível"
downloadingButton = "Baixando.."
downloadButton = 'Baixar do GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Feche o launcher e execute o dmg para atualizar.</span>'
latestVersionTitle = "Você Está Usando a Versão Mais Recente"
checkForUpdatesButton = "Verificar Atualizações"
checkingForUpdatesButton = "Verificando Atualizações.."

[js.settings.msftLogin]
errorTitle = "Falha no Login Microsoft"
errorMessage = "Não conseguimos autenticar sua conta Microsoft. Por favor, tente novamente."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Não Foi Possível Carregar o Índice de Distribuição"
fatalErrorMessage = "Não foi possível estabelecer uma conexão com nossos servidores para baixar o índice de distribuição. Nenhuma cópia local estava disponível para carregar. <br><br>O índice de distribuição é um arquivo essencial que fornece as informações mais recentes do servidor. O launcher não pode iniciar sem ele. Certifique-se de estar conectado à internet e reinicie o aplicativo."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao Atualizar Login"
failedMessage = "Não conseguimos atualizar o login para <strong>{account}</strong>. Por favor, selecione outra conta ou faça login novamente."
failedMessageSelectAnotherAccount = "Não conseguimos atualizar o login para <strong>{account}</strong>. Por favor, faça login novamente."
loginButton = "Entrar"
selectAnotherAccountButton = "Selecionar Outra Conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações..."
installNowButton = "Instalar Agora"
checkForUpdatesButton = "Verificar Atualizações"

[js.auth.microsoft.error]
noProfileTitle = "Erro Durante o Login:<br>Perfil Não Configurado"
noProfileDesc = "Sua conta Microsoft ainda não tem um perfil do Minecraft configurado. Se você comprou recentemente o jogo ou o resgatou através do Xbox Game Pass, você deve configurar seu perfil em <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Se você ainda não comprou o jogo, você também pode fazê-lo em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erro Durante o Login:<br>Nenhuma Conta Xbox"
noXboxAccountDesc = "Sua conta Microsoft não tem uma conta Xbox associada."
xblBannedTitle = "Erro Durante o Login:<br>Xbox Live Indisponível"
xblBannedDesc = "Sua conta Microsoft é de um país onde o Xbox Live não está disponível ou está bloqueado."
under18Title = "Erro Durante o Login:<br>Aprovação Parental Necessária"
under18Desc = "Contas de usuários com menos de 18 anos devem ser adicionadas a uma Família por um adulto."
unknownTitle = "Erro Desconhecido Durante o Login"
unknownDesc = "Ocorreu um erro desconhecido. Por favor, verifique o console para mais detalhes."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erro Interno:<br>Método Não Permitido"
methodNotAllowedDesc = "Método não permitido. Por favor, reporte este erro."
notFoundTitle = "Erro Interno:<br>Não Encontrado"
notFoundDesc = "O endpoint de autenticação não foi encontrado. Por favor, reporte este problema."
accountMigratedTitle = "Erro Durante o Login:<br>Conta Migrada"
accountMigratedDesc = "Você tentou fazer login com uma conta migrada. Tente novamente usando o e-mail da conta como nome de usuário."
invalidCredentialsTitle = "Erro Durante o Login:<br>Credenciais Inválidas"
invalidCredentialsDesc = "O e-mail ou senha que você inseriu está incorreto. Por favor, tente novamente."
tooManyAttemptsTitle = "Erro Durante o Login:<br>Excesso de Tentativas"
tooManyAttemptsDesc = "Houve muitas tentativas de login com esta conta recentemente. Por favor, tente novamente mais tarde."
invalidTokenTitle = "Erro Durante o Login:<br>Token Inválido"
invalidTokenDesc = "O token de acesso fornecido é inválido."
tokenHasProfileTitle = "Erro Durante o Login:<br>Token Já Possui Perfil"
tokenHasProfileDesc = "O token de acesso já tem um perfil atribuído. A seleção de perfis ainda não está implementada."
credentialsMissingTitle = "Erro Durante o Login:<br>Credenciais Faltando"
credentialsMissingDesc = "Nome de usuário/senha não foi enviado ou a senha tem menos de 3 caracteres."
invalidSaltVersionTitle = "Erro Durante o Login:<br>Versão de Sal Inválida"
invalidSaltVersionDesc = "Versão de sal inválida."
unsupportedMediaTypeTitle = "Erro Interno:<br>Tipo de Mídia Não Suportado"
unsupportedMediaTypeDesc = "Tipo de mídia não suportado. Por favor, reporte este erro."
accountGoneTitle = "Erro Durante o Login:<br>Conta Migrada"
accountGoneDesc = "A conta foi migrada para uma conta Microsoft. Por favor, faça login com Microsoft."
unreachableTitle = "Erro Durante o Login:<br>Inacessível"
unreachableDesc = "Não foi possível acessar os servidores de autenticação. Certifique-se de que estão online e você está conectado à internet."
gameNotPurchasedTitle = "Erro Durante o Login:<br>Jogo Não Comprado"
gameNotPurchasedDesc = "A conta com a qual você está tentando fazer login não comprou uma cópia do Minecraft. Você pode comprar uma cópia em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Erro Desconhecido Durante o Login"
unknownErrorDesc = "Ocorreu um erro desconhecido. Por favor, verifique o console para mais detalhes."